### Mysql setting ###
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/template?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: mingyu
    password: mingyu98

  ### jpa setting ###
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect

  ### spring security ###
  security:
    user:
      name: gyu
      password: gyugyugyugyugyugyutemplatetemplate
    #      roles: USER, ADMIN

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa